"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

type Language = "ar" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: "rtl" | "ltr";
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    dashboard: "لوحة التحكم",
    properties: "العقارات",
    units: "الوحدات",
    tenants: "المستأجرين",
    finance: "النظام المالي",
    leases: "العقود",
    payments: "المدفوعات",
    installments: "الأقساط",
    receipts: "السندات",
    reports: "التقارير",
    settings: "الإعدادات",
    users: "المستخدمين",
    logout: "تسجيل الخروج",
    
    chart_of_accounts: "دليل الحسابات",
    journal_entries: "قيود اليومية",
    trial_balance: "ميزان المراجعة",
    income_statement: "قائمة الدخل",
    balance_sheet: "الميزانية العمومية",
    cash_flow: "التدفق النقدي",
    budgets: "الموازنات",
    reconciliation: "التسويات البنكية",
    ar_aging: "أعمار الديون",
    ar: "حسابات العملاء",
    ap: "حسابات الموردين",
    
    add_property: "إضافة عقار",
    new_entry: "قيد جديد",
    export: "تصدير",
    save: "حفظ",
    cancel: "إلغاء",
    loading: "جاري التحميل...",
    
    total_revenue: "إجمالي الإيرادات",
    occupancy_rate: "نسبة الإشغال",
    active_leases: "العقود النشطة",
    cash_position: "المركز النقدي",
    outstanding_ar: "المستحقات المعلقة",
    portfolio_overview: "نظرة عامة على المحفظة",
    portfolio_description: "راقب أداء عقاراتك وصحتك المالية في الوقت الفعلي.",
    revenue_vs_expenses: "الإيرادات مقابل المصروفات",
    monthly_trend: "مقارنة الشهري للتدفق المالي",
    ar_aging_title: "أعمار الديون",
    ar_status: "تحليل التحصيلات المعلقة",
    recent_transactions: "آخر العمليات",
    view_all: "عرض الكل",
    quick_actions: "إجراءات سريعة",
    total: "إجمالي",
    net_income: "صافي الدخل",
    budget_utilization: "استهلاك الميزانية",
    remaining: "المتبقي",
    target_vs_actual: "الهدف مقابل الفعلي",
    
    tenant: "المستأجر",
    unit: "الوحدة",
    amount: "المبلغ",
    status: "الحالة",
    date: "التاريخ",
    type: "النوع",
    
    record_payment: "قبض دفعة",
    new_lease: "عقد جديد",
    add_tenant: "إضافة مستأجر",
    finance_reports: "تقارير مالية",
    export_data: "تصدير البيانات",

    finance_center: "المركز المالي",
    live_data: "بيانات حية ومحدثة",
    net_income_current: "صافي الدخل للفترة",
    receivables: "مستحقات القبض",
    payables: "حسابات الدفع",
    remaining_budget: "الميزانية المتبقية",
    revenue_trend: "اتجاه الإيرادات والمصروفات",
    last_12_periods: "آخر 12 فترة مالية",
    ar_distribution: "توزيع أعمار الديون",
    top_revenue_properties: "أعلى العقارات بالإيرادات",
    vs_last_month: "مقابل الشهر الماضي",
    current_period: "للفترة الحالية",
    total_liquidity: "إجمالي السيولة",
    active_debts: "ديون المستأجرين",
    vendor_balance: "ديون الموردين",
    annual_plan: "من الموازنة السنوية",
    
    // Tenants Registry
    tenants_registry: "سجل المستأجرين",
    tenants_description: "إدارة بيانات المستأجرين والتوثيق القانوني المركزي",
    import_excel: "رفع إكسل",
    search_tenants_placeholder: "بحث عن مستأجر بالاسم، البريد، أو رقم الهاتف...",
    loading_tenants: "جاري جلب قائمة المستأجرين...",
    no_tenants_title: "لا توجد بيانات حالياً",
    no_tenants_desc: "ابدأ بتوثيق المستأجر الأول لبدء التنظيم القانوني.",
    tenant_profile: "الملف الشخصي للمستأجر",
    contact_info: "بيانات الاتصال",
    legal_docs: "التوثيق القانوني",
    id_type: "نوع الهوية",
    id_number: "رقم الهوية",
    nationality: "الجنسية",
    address: "العنوان",
    tenant_attachments: "مرفقات المستأجر",
    add_documents: "إضافة مستندات",
    contract_activity: "النشاط التعاقدي",
    export_profile_pdf: "استخراج ملف المستأجر (PDF)",
    first_name: "الاسم الأول",
    last_name: "اسم العائلة",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    register_tenant: "تسجيل مستأجر",
    save_tenant_data: "توثيق البيانات",
    address_not_available: "العنوان غير متوفر",

    // Units
    manage_units: "إدارة الوحدات",
    units_description: "تصنيف وتنظيم الوحدات العقارية ضمن الصروح السكنية والتجارية",
    add_new_unit: "إضافة وحدة جديدة",
    search_units_placeholder: "بحث عن وحدة برقمها أو نوعها...",
    loading_units: "جاري جلب الوحدات المتاحة...",
    no_units_title: "لا توجد وحدات مسجلة",
    no_units_desc: "ابدأ بربط الوحدات العقارية بمشاريعك الكبرى.",
    unit_number: "رقم الوحدة",
    parent_property: "العقار التابع",
    unit_type: "نوع الوحدة",
    floor: "الطابق",
    area: "المساحة",
    bedrooms: "الغرف",
    bathrooms: "الحمامات",
    unit_details: "تفاصيل الوحدة العقارية",
    unit_attachments: "مرفقات الوحدة",
    unit_docs_photos: "وثائق الوحدة وصورها",
    sqm: "م²",
    per_month: "شهرياً",
    extract_unit_card: "استخراج بطاقة الوحدة",
    select_property: "اختر العقار المستهدف",
    unit_number_placeholder: "مثال: شقة 104",
    unit_occupied_desc: "الوحدة مشغولة حالياً بموجب عقد إيجار فعال.",

    // Unit Types
    APARTMENT: "شقة سكنية",
    SHOP: "محل تجاري",
    OFFICE: "مكتب إداري",
    VILLA: "فيلا ملكية",
    WAREHOUSE: "مخزن لوجستي",

    // Unit Statuses
    AVAILABLE: "شاغرة",
    RENTED: "مؤجرة",
    MAINTENANCE: "صيانة",
    
    units_management: "إدارة الوحدات",
    add_unit: "إضافة وحدة",
    search_units: "بحث في الوحدات...",
    all: "الكل",
    all_properties: "جميع العقارات",
    monthly_rent: "الإيجار الشهري",
    attachments: "المرفقات",
    goal: "الهدف",

    // General
    confirm_delete: "هل أنت متأكد من الحذف؟",
    success_import: "تم الاستيراد بنجاح",
    close: "إغلاق",
    confirm: "تأكيد",
    actions: "الإجراءات",
    revenue: "الإيرادات",
    net_profit: "صافي الربح",
    occupancy: "الإشغال",
    edit: "تعديل",
    archive: "أرشفة",
    delete: "حذف",
    active: "نشط",
    inactive: "غير نشط",
    view_details: "عرض التفاصيل",
    all_status: "كل الحالات",
    city: "المدينة",
    search_properties: "بحث في العقارات...",

    // Properties
    properties_portfolio: "محفظة العقارات",
    properties_description: "إدارة الأصول العقارية، تتبع الإشغال، وتحصيل الإيرادات لكل أصل.",
    property_name: "اسم العقار",
    location: "الموقع",
    general_info: "معلومات عامة",
    legal_records: "السجلات القانونية",
    ownership_type: "نوع الملكية",
    record_number: "رقم السجل",
    record_date: "تاريخ السجل",
    issuer_directorate: "الجهة المصدرة",
    total_area_sqm: "المساحة الإجمالية (م²)",
    record_property: "تسجيل العقار",
    units_count: "عدد الوحدات",

    // Cities
    Basra: "البصرة",
    
    // Detailed Sanad Fields
    issuer: "الجهة المصدرة",
    registration_directorate: "مديرية التسجيل العقاري في",
    form_type: "نوع النموذج",
    current_record_desc: "وصف السجل العقاري الدائمي الحالي",
    governorate: "المحافظة",
    district: "القضاء",
    sub_district: "الناحية",
    street: "الشارع",
    number: "العدد",
    sanad_date: "التاريخ",
    volume_number: "رقم المجلد",
    prev_record_desc: "وصف السجل العقاري الدائمي المنقول منه",
    property_sequence: "تسلسل العقار",
    neighborhood_name: "اسم المحلة",
    location_details: "تفاصيل الموقع (الباب / القطعة / المقاطعة)",
    plot_number: "رقم القطعة",
    section_number: "رقم المقاطعة",
    section_name: "اسم المقاطعة",
    door_number: "رقم الباب",
    ownership_details: "تفاصيل الملكية والعقار",
    owner_nationality: "المالك أو المتصرف وتابعيته",
    boundaries: "الحدود",
    property_gender: "جنس العقار",
    property_type_detailed: "نوع العقار (الصنف)",
    contents: "المشتملات",
    easements: "حقوق الارتفاق والعقر",
    area_details: "تفاصيل المساحة",
    area_sqm: "متر مربع",
    area_olk: "اولك",
    area_donum: "دونم",
    registration_details: "تفاصيل التسجيل",
    registration_nature: "ماهية التسجيل ومستنداته",
    insurance_notes: "اشارات التأمينات والحجز",
    deed_ruling: "حكم السند",
    certifications: "التصديقات",
    requesting_entity_student: "الجهة الطالبة للصورة",
    certification_date_manual: "التاريخ (يدوي)",
    seals: "الأختام",
    mandatory: "اجباري",
    optional: "اختياري",
  },
  en: {
    dashboard: "Dashboard",
    properties: "Properties",
    units: "Units",
    tenants: "Tenants",
    finance: "Finance System",
    leases: "Leases",
    payments: "Payments",
    installments: "Installments",
    receipts: "Receipts",
    reports: "Reports",
    settings: "Settings",
    users: "Users",
    logout: "Logout",
    
    chart_of_accounts: "Chart of Accounts",
    journal_entries: "Journal Entries",
    trial_balance: "Trial Balance",
    income_statement: "Income Statement",
    balance_sheet: "Balance Sheet",
    cash_flow: "Cash Flow",
    budgets: "Budgets",
    reconciliation: "Bank Reconciliation",
    ar_aging: "AR Aging",
    ar: "Accounts Receivable",
    ap: "Accounts Payable",
    
    add_property: "Add Property",
    new_entry: "New Entry",
    export: "Export",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    
    total_revenue: "Total Revenue",
    occupancy_rate: "Occupancy Rate",
    active_leases: "Active Leases",
    cash_position: "Cash Position",
    outstanding_ar: "Outstanding AR",
    portfolio_overview: "Portfolio Overview",
    portfolio_description: "Monitor your real estate performance and financial health in real-time.",
    revenue_vs_expenses: "Revenue vs Expenses",
    monthly_trend: "Monthly financial flow comparison",
    ar_aging_title: "AR Aging Breakdown",
    ar_status: "Status of pending collections",
    recent_transactions: "Recent Transactions",
    view_all: "View All",
    quick_actions: "Quick Actions",
    total: "Total",
    net_income: "Net Income",
    budget_utilization: "Budget Utilization",
    remaining: "Remaining",
    target_vs_actual: "Target vs Actual",
    
    tenant: "Tenant",
    unit: "Unit",
    amount: "Amount",
    status: "Status",
    date: "Date",
    type: "Type",
    
    record_payment: "Record Payment",
    new_lease: "New Lease",
    add_tenant: "Add Tenant",
    finance_reports: "Finance Reports",
    export_data: "Export Data",
    
    finance_center: "Finance Center",
    live_data: "Live and updated data",
    net_income_current: "Net Income for period",
    receivables: "Receivables (AR)",
    payables: "Payables (AP)",
    remaining_budget: "Remaining Budget",
    revenue_trend: "Revenue & Expense Trends",
    last_12_periods: "Last 12 fiscal periods",
    ar_distribution: "Debt Aging Distribution",
    top_revenue_properties: "Top Revenue Properties",
    vs_last_month: "Vs last month",
    current_period: "Current period",
    total_liquidity: "Total liquidity",
    active_debts: "Active tenant debts",
    vendor_balance: "Vendor balance",
    annual_plan: "Of annual budget",

    tenants_registry: "Tenants Registry",
    tenants_description: "Manage tenant records and central legal documentation.",
    import_excel: "Import Excel",
    search_tenants_placeholder: "Search by name, email, or phone...",
    loading_tenants: "Fetching tenant records...",
    no_tenants_title: "No data available",
    no_tenants_desc: "Start by documenting your first tenant to begin legal organization.",
    tenant_profile: "Tenant Profile",
    contact_info: "Contact Information",
    legal_docs: "Legal Documentation",
    id_type: "ID Type",
    id_number: "ID Number",
    nationality: "Nationality",
    address: "Address",
    tenant_attachments: "Tenant Attachments",
    add_documents: "Add Documents",
    contract_activity: "Contractual Activity",
    export_profile_pdf: "Export Profile (PDF)",
    first_name: "First Name",
    last_name: "Last Name",
    email: "Email",
    phone: "Phone",
    register_tenant: "Register Tenant",
    save_tenant_data: "Save Documentation",
    address_not_available: "Address not available",

    manage_units: "Manage Units",
    units_description: "Categorize and organize property units within residential and commercial structures.",
    add_new_unit: "Add New Unit",
    search_units_placeholder: "Search by unit number or type...",
    loading_units: "Fetching available units...",
    no_units_title: "No units registered",
    no_units_desc: "Start by linking property units to your major projects.",
    unit_number: "Unit Number",
    parent_property: "Parent Property",
    unit_type: "Unit Type",
    floor: "Floor",
    area: "Area",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    unit_details: "Unit Details",
    unit_attachments: "Unit Attachments",
    unit_docs_photos: "Unit Documents & Photos",
    sqm: "m²",
    per_month: "Per Month",
    extract_unit_card: "Extract Unit Card",
    select_property: "Select Target Property",
    unit_number_placeholder: "e.g. Apt 104",
    unit_occupied_desc: "The unit is currently occupied under an active lease.",

    APARTMENT: "Apartment",
    SHOP: "Shop",
    OFFICE: "Office",
    VILLA: "Villa",
    WAREHOUSE: "Warehouse",

    AVAILABLE: "Available",
    RENTED: "Rented",
    MAINTENANCE: "Maintenance",

    units_management: "Units Management",
    add_unit: "Add Unit",
    search_units: "Search units...",
    all: "All",
    all_properties: "All Properties",
    monthly_rent: "Monthly Rent",
    attachments: "Attachments",
    goal: "Goal",

    confirm_delete: "Are you sure you want to delete?",
    success_import: "Imported successfully",
    close: "Close",
    confirm: "Confirm",
    actions: "Actions",
    revenue: "Revenue",
    net_profit: "Net Profit",
    occupancy: "Occupancy",
    edit: "Edit",
    archive: "Archive",
    delete: "Delete",
    active: "Active",
    inactive: "Inactive",
    view_details: "View Details",
    all_status: "All Status",
    city: "City",
    search_properties: "Search properties...",

    properties_portfolio: "Properties Portfolio",
    properties_description: "Manage real estate assets, track occupancy, and revenue collection per asset.",
    property_name: "Property Name",
    location: "Location",
    general_info: "General Info",
    legal_records: "Legal Records",
    ownership_type: "Ownership Type",
    record_number: "Record Number",
    record_date: "Record Date",
    issuer_directorate: "Issuer Directorate",
    total_area_sqm: "Total Area (SQM)",
    record_property: "Record Property",
    units_count: "Units Count",

    Basra: "Basra",

    // Detailed Sanad Fields
    issuer: "Issuer",
    registration_directorate: "Real Estate Reg Directorate",
    form_type: "Form Type",
    current_record_desc: "Current Permanent Record Description",
    governorate: "Governorate",
    district: "District",
    sub_district: "Sub-district",
    street: "Street",
    number: "Number",
    sanad_date: "Date",
    volume_number: "Volume Number",
    prev_record_desc: "Transferred From Record Description",
    property_sequence: "Property Sequence",
    neighborhood_name: "Neighborhood Name",
    location_details: "Location Details (Door/Plot/Section)",
    plot_number: "Plot Number",
    section_number: "Section Number",
    section_name: "Section Name",
    door_number: "Door Number",
    ownership_details: "Ownership & Property Details",
    owner_nationality: "Owner & Nationality",
    boundaries: "Boundaries",
    property_gender: "Property Gender",
    property_type_detailed: "Property Category",
    contents: "Contents",
    easements: "Easements",
    area_details: "Area Details",
    area_sqm: "Sqm",
    area_olk: "Olk",
    area_donum: "Donum",
    registration_details: "Registration Details",
    registration_nature: "Registration Nature",
    insurance_notes: "Insurance/Lien Notes",
    deed_ruling: "Deed Ruling",
    certifications: "Certifications",
    requesting_entity_student: "Requesting Entity",
    certification_date_manual: "Date (Manual)",
    seals: "Seals",
    mandatory: "Mandatory",
    optional: "Optional",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar");

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language;
    if (saved) setLanguageState(saved);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  };

  const t = (key: string) => translations[language][key] || key;
  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      <div dir={dir} className={language === "ar" ? "font-arabic" : ""}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
}
